# Generated by Django 5.0.2 on 2024-04-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_alter_registration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeresume',
            field=models.FileField(default='default_resume.pdf', upload_to='EmployeResume/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
