# Generated by Django 5.0.2 on 2024-04-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_fail_employee_age_employee_employeeresume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empphoto',
            field=models.FileField(default='default_resume.pdf', upload_to='EmployeResume/'),
        ),
    ]
